# Generated by Django 4.2 on 2024-01-07 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_postlikecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikecomment',
            name='like',
        ),
        migrations.AddField(
            model_name='postlikecomment',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='postlikecomment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
