# Generated by Django 4.2 on 2024-01-07 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_postlikecomment_like_postlikecomment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikecomment',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.feedpost'),
        ),
    ]
