# Generated by Django 4.2 on 2024-01-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='profile_photo',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
