# Generated by Django 4.2 on 2023-12-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics'), ('Food', 'Food')], max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='postdata',
            name='content_type',
            field=models.ManyToManyField(to='users_register.contenttype'),
        ),
    ]
