# Generated by Django 4.2 on 2023-12-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_register', '0002_contenttype_postdata_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ContentType',
        ),
        migrations.AddField(
            model_name='postdata',
            name='content_type',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics'), ('Food', 'Food')], max_length=100, null=True),
        ),
    ]
