# Generated by Django 4.2 on 2024-02-02 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_register', '0002_alter_myprofile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='created',
        ),
    ]
