# Generated by Django 4.2 on 2024-01-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_register', '0004_commentdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='CommentData',
        ),
        migrations.DeleteModel(
            name='PostData',
        ),
    ]
