# Generated by Django 4.2 on 2024-01-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_register', '0007_myprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
