# Generated by Django 4.2 on 2024-01-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_register', '0008_myprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
